### ISSUE TITLE
KiteConnect error?

### ISSUE THREAD

**Issue by BasharAG** [yudhvir/PyTrading#1]
I installed kiteconnect using pip and pip3 as well, yet when I run main.py, I get this error:
```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from kite_connect import kite_init,start_ticking
ImportError: No module named kite_connect
```

**Comment by yudhv** [comment]
`kite_connect.py` is a custom python file, and is different from `kiteconnect` the API. I haven't included the custom `kite_connect` file because it contained my personal API key and secret key that are needed to instantiate `kiteconnect`. 

Sorry for not including the fact in the README, but all you need to do is instantiate a `kiteconnect` instance with your own subscription credentials and call `tick_init(key,public_token,user_id)` that is present in the file `tick_data.py`.

**Comment by darshansk** [comment]
I understand the file has your personal details but can you share the kite_connect file after removing the credentials? It will be of great use if you could show us the code. I just need references to how the functions kite_init and kite_connect work.

**Comment by vanshji** [comment]
Hi can you explain how to install and use it?
